--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

-- Started on 2025-06-13 10:13:35

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 4865 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 219 (class 1259 OID 16429)
-- Name: BookDetails; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."BookDetails" (
    "Id" integer NOT NULL,
    "Title" text,
    "Description" text,
    "Author" text
);


ALTER TABLE public."BookDetails" OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 16428)
-- Name: BookDetails_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."BookDetails" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."BookDetails_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16437)
-- Name: Users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Users" (
    "Id" integer NOT NULL,
    "Name" text,
    "Email" text,
    "Password" text,
    "Role" text
);


ALTER TABLE public."Users" OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16436)
-- Name: Users_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Users" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Users_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 16412)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 4857 (class 0 OID 16429)
-- Dependencies: 219
-- Data for Name: BookDetails; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."BookDetails" ("Id", "Title", "Description", "Author") FROM stdin;
19	string	string	string
\.


--
-- TOC entry 4859 (class 0 OID 16437)
-- Dependencies: 221
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Users" ("Id", "Name", "Email", "Password", "Role") FROM stdin;
2	str	str@str	pass	string
1	string	string	string	string
100	himani	hi@hi	hi	admin
99	ram	ram@ram	ram	manager
\.


--
-- TOC entry 4855 (class 0 OID 16412)
-- Dependencies: 217
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20250602043727_Initials	8.0.16
20250529050718_Initial	8.0.16
20250602091909_RecreateBookDetails	8.0.16
\.


--
-- TOC entry 4866 (class 0 OID 0)
-- Dependencies: 218
-- Name: BookDetails_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."BookDetails_Id_seq"', 1, false);


--
-- TOC entry 4867 (class 0 OID 0)
-- Dependencies: 220
-- Name: Users_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Users_Id_seq"', 1, true);


--
-- TOC entry 4707 (class 2606 OID 16435)
-- Name: BookDetails PK_BookDetails; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BookDetails"
    ADD CONSTRAINT "PK_BookDetails" PRIMARY KEY ("Id");


--
-- TOC entry 4709 (class 2606 OID 16443)
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- TOC entry 4705 (class 2606 OID 16416)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


-- Completed on 2025-06-13 10:13:35

--
-- PostgreSQL database dump complete
--

